# Dockerfile.dev
FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache vips-dev build-base

COPY package*.json ./
RUN npm install

COPY . .

RUN mkdir -p /app/uploads

EXPOSE 3000

CMD ["npm", "run", "dev"]
